name: registry

services:
  registry-ui:
    container_name: registry-ui
    image: ghcr.io/eznix86/docker-registry-ui:0.5.5
    environment:
      REGISTRY_URL: http://registry-server:5000
    ports:
      - "5055:80"
    restart: unless-stopped

  registry-server:
    container_name: registry-server
    image: registry:2.8.3
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
    ports:
      - "5050:5000"
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/registry
