services:
  docker-registry:
    ports: []
    networks:
      - proxy

  docker-registry-ui:
    ports: []
    environment:
      REGISTRY_URL: ${REGISTRY_PUBLIC_URL:?error}
    networks:
      - proxy

networks:
  proxy:
    external: true
