services:
  docker-registry:
    ports: []
    networks:
      - proxy

  docker-registry-ui:
    environment:
      REGISTRY_URL: http://${REGISTRY_PUBLIC_HOST:?error}
    ports: []
    networks:
      - proxy

networks:
  proxy:
    external: true
