# UP: docker-compose -f .\docker-compose.yml up -d --build --force-recreate
# STOP: docker-compose -f .\docker-compose.yml stop
# START: docker-compose -f .\docker-compose.yml start
# DOWN: docker-compose -f .\docker-compose.yml down -v --rmi all

services:
  rabbitmq:
    container_name: rabbitmq
    build:
      dockerfile: ./Rabbitmq.dockerfile
    image: i_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 5672:5672
      - 15672:15672
      - 15675:15675
    volumes:
      - ./logs:/var/log

