# RUN: docker-compose -f .\docker-compose.yml --env-file .env up -d --build
# STOP: docker-compose -f .\docker-compose.yml stop
# START: docker-compose -f .\docker-compose.yml start
# CLEAN: docker-compose -f .\docker-compose.yml down -v

version: "3.8"

services:
  mongodb:
    container_name: mongodb
    build:
      context: ./
      dockerfile: ./Dockerfile.mongodb
    image: i_mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

  mongo-express:
    container_name: mongoexpress
    build:
      context: ./
      dockerfile: ./Dockerfile.mongoexpress
    image: i_mongoexpress
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb

