# UP: docker-compose -f .\docker-compose.yml up -d --build --force-recreate
# STOP: docker-compose -f .\docker-compose.yml stop
# START: docker-compose -f .\docker-compose.yml start
# DOWN: docker-compose -f .\docker-compose.yml down -v --rmi all

services:
  hbbr:
    container_name: hbbr
    ports:
      - 21117:21117
      - 21119:21119
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    networks:
      - rustdesk-net
    restart: unless-stopped

  hbbs:
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r 127.0.0.1:21117
    volumes:
      - ./data:/root
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: unless-stopped

networks:
  rustdesk-net:
    external: false