# UP: docker-compose -f .\docker-compose.yml up -d --build --force-recreate
# STOP: docker-compose -f .\docker-compose.yml stop
# START: docker-compose -f .\docker-compose.yml start
# DOWN: docker-compose -f .\docker-compose.yml down -v --rmi all

services:
  nginx:
    container_name: nginx
    build:
      dockerfile: ./Nginx.dockerfile
    image: "i_nginx"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data:/var/www:ro
      - ./confs/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./confs/nginx.conf:/etc/nginx/nginx.conf:ro

