# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
name: share

services:
  share-server:
    container_name: share-server
    image: tanq16/local-content-share:main
    ports:
      - "9999:8080"
    restart: unless-stopped
    volumes:
      - ./data:/app/data