name: verdaccio

services:
  verdaccio:
    container_name: verdaccio
    image: verdaccio/verdaccio:5
    ports:
      - 4848:4873
    restart: unless-stopped
    volumes:
      - ./data/config.yml:/verdaccio/conf/config.yaml
      - ./data/htpasswd:/verdaccio/htpasswd
      - ./data/storage:/verdaccio/storage
      - ./data/plugins:/verdaccio/plugins