# UP: docker-compose -f .\docker-compose.yml up -d --build --force-recreate
# STOP: docker-compose -f .\docker-compose.yml stop
# START: docker-compose -f .\docker-compose.yml start
# DOWN: docker-compose -f .\docker-compose.yml down -v --rmi all

services:
  postgres:
    container_name: postgres
    build:
      dockerfile: ./Postgres.dockerfile
    image: i_postgres
    ports:
      - 5432:5432
    command: ["postgres", "-c", "log_statement=all"] 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_NAME: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./logs:/var/log

